#!/usr/bin/env python3
"""
Scan repository for TODO/FIXME comments and generate a Markdown report.

Usage: python tools/generate_todo_report.py
Produces: docs/TODO_FIXME_REPORT.md
"""
import os
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
# Use PWD to match user's shell location (avoids resolving symlinks to Trash/cloud storage)
import os
root_path_str = os.getenv('PWD') or os.getcwd()
ROOT = Path(root_path_str)
OUT = ROOT / "docs" / "TODO_FIXME_REPORT.md"

# Ensure docs directory exists
if not OUT.parent.exists():
    OUT.parent.mkdir(parents=True, exist_ok=True)

PATTERN = re.compile(r"\b(TODO|FIXME)\b", re.IGNORECASE)

def is_text_file(path: Path) -> bool:
    try:
        with open(path, 'rb') as f:
            chunk = f.read(4096)
            if b"\0" in chunk:
                return False
    except Exception:
        return False
    return True

def classify(text: str) -> str:
    t = text.lower()
    hints_complex = [
        'design', 'refactor', 'race', 'concurrent', 'abort', 'retry', 'performance',
        'memory', 'security', 'validate', 'schema', 'generic', 'nuke', 'inefficient',
        'algorithm', 'thread', 'blocking', 'async', 'validate', 'jwt', 'schema', 'hack'
    ]
    hints_trivial = ['typo', 'wrap', 'link', 'format', 'docs', 'documentation', 'spell', 'grammar']
    if any(h in t for h in hints_trivial):
        return 'trivial'
    if any(h in t for h in hints_complex):
        return 'complex'
    # if contains words like 'should' or 'maybe' consider implementable
    if 'should' in t or 'maybe' in t or 'add' in t or 'implement' in t or 'todo:' in t:
        return 'implementable'
    return 'unknown'

def scan(root: Path):
    results = []
    for p in root.rglob('*'):
        if p.is_dir():
            if p.name in ('.git', 'build', 'node_modules', '.venv', 'venv'):
                continue
        else:
            if not is_text_file(p):
                continue
            try:
                text = p.read_text(encoding='utf-8')
            except Exception:
                try:
                    text = p.read_text(encoding='latin-1')
                except Exception:
                    continue
            lines = text.splitlines()
            for i, line in enumerate(lines, start=1):
                if PATTERN.search(line):
                    before = '\n'.join(lines[max(0, i-3):i-1])
                    after = '\n'.join(lines[i:i+2])
                    whole = '\n'.join(lines[max(0, i-3):min(len(lines), i+2)])
                    tag = PATTERN.search(line).group(1)
                    cls = classify(line + ' ' + whole)
                    results.append({
                        'path': str(p.relative_to(root)),
                        'line': i,
                        'tag': tag,
                        'text': line.strip(),
                        'context': whole,
                        'classification': cls,
                    })
    return results

def generate_md(results):
    OUT.parent.mkdir(parents=True, exist_ok=True)
    by_class = {}
    for r in results:
        by_class.setdefault(r['classification'], []).append(r)

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('# TODO/FIXME Report\n\n')
        f.write('Generated by `tools/generate_todo_report.py`.\n\n')
        f.write('Summary:\n\n')
        for k in sorted(by_class.keys()):
            f.write(f'- **{k}**: {len(by_class[k])} items\n')
        f.write('\n---\n\n')

        for k in sorted(by_class.keys()):
            f.write(f'## {k.capitalize()} ({len(by_class[k])})\n\n')
            for item in by_class[k]:
                f.write(f'- **{item["tag"]}** in `{item["path"]}`:{item["line"]} — {item["text"]}\n')
                f.write('```\n')
                f.write(item['context'] + '\n')
                f.write('```\n\n')

        f.write('\n---\n\n')
        f.write('Notes:\n')
        f.write('- `trivial`: likely simple fixes (typos, docs).\n')
        f.write('- `implementable`: small code changes may resolve.\n')
        f.write('- `complex`: needs design review or larger refactor.\n')
        f.write('- `unknown`: manual review recommended.\n')

    print(f'Wrote report to {OUT}')

def main():
    results = scan(ROOT)
    generate_md(results)

if __name__ == '__main__':
    main()
